#!/bin/bash

mawk_prog_first='BEGIN { skip = 0; re_str = "^\/\*+\/$"; }
{
	if (skip)
	{
		if (!match($0, re_str)) skip = 0;
	}
	else if (match($0, re_str)) skip = 1;
	else print $0;
}'

mawk_prog_rest='BEGIN { line = 0; skip = 0; re_str = "^\/\*+\/$"; }
{
	if (line < 19) ++line;
	else
	{
		if (skip)
		{
			if (!match($0, re_str)) skip = 0;
		}
		else if (match($0, re_str)) skip = 1;
		else print $0;
	}
}'

mawk "$mawk_prog_first" "define_macros.hpp"               >  "single_source/01_generator.hpp" &&

mawk "$mawk_prog_rest"  "01_generator/00_graph.hpp"       >> "single_source/01_generator.hpp" &&
mawk "$mawk_prog_rest"  "01_generator/01_lexer.hpp"       >> "single_source/01_generator.hpp" &&
mawk "$mawk_prog_rest"  "01_generator/02_syntax.hpp"      >> "single_source/01_generator.hpp" &&
mawk "$mawk_prog_rest"  "01_generator/03_parser.hpp"      >> "single_source/01_generator.hpp" &&
mawk "$mawk_prog_rest"  "01_generator/04_parse_table.hpp" >> "single_source/01_generator.hpp" &&

mawk "$mawk_prog_rest"  "undef_macros.hpp"                >> "single_source/01_generator.hpp"

