#!/bin/bash

mawk_prog_first='BEGIN { skip = 0; re_str = "^\/\*+\/$"; }
{
	if (skip)
	{
		if (!match($0, re_str)) skip = 0;
	}
	else if (match($0, re_str)) skip = 1;
	else print $0;
}'

mawk_prog_rest='BEGIN { line = 0; skip = 0; re_str = "^\/\*+\/$"; }
{
	if (line < 19) ++line;
	else
	{
		if (skip)
		{
			if (!match($0, re_str)) skip = 0;
		}
		else if (match($0, re_str)) skip = 1;
		else print $0;
	}
}'

mawk "$mawk_prog_first" "define_macros.hpp"           >  "single_source/01_chord.hpp" &&

mawk "$mawk_prog_rest"  "01_chord/00_lexer.hpp"       >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/01_scanner.hpp"     >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/02_syntax.hpp"      >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/03_action.hpp"      >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/04_parser.hpp"      >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/05_chain.hpp"       >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/06_lookup.hpp"      >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/07_cycle.hpp"       >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/08_progression.hpp" >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/09_machine.hpp"     >> "single_source/01_chord.hpp" &&
mawk "$mawk_prog_rest"  "01_chord/10_targeter.hpp"    >> "single_source/01_chord.hpp" &&

mawk "$mawk_prog_rest"  "undef_macros.hpp"            >> "single_source/01_chord.hpp"

