#!/bin/bash

mawk_prog_first='BEGIN { skip = 0; re_str = "^\/\*+\/$"; }
{
	if (skip)
	{
		if (!match($0, re_str)) skip = 0;
	}
	else if (match($0, re_str)) skip = 1;
	else print $0;
}'

mawk_prog_rest='BEGIN { line = 0; skip = 0; re_str = "^\/\*+\/$"; }
{
	if (line < 19) ++line;
	else
	{
		if (skip)
		{
			if (!match($0, re_str)) skip = 0;
		}
		else if (match($0, re_str)) skip = 1;
		else print $0;
	}
}'

mawk "$mawk_prog_first" "define_macros.hpp"          >  "cpp_cctmp_library.hpp" &&

mawk "$mawk_prog_rest"  "00_cctmp_grammar.hpp"       >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "01_cctmp_argument.hpp"      >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "02_cctmp_parameter.hpp"     >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "03_cctmp_praxis.hpp"        >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "04_cctmp_interpreter.hpp"   >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "05_cctmp_machine.hpp"       >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "06_cctmp_lexer.hpp"         >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "07_cctmp_parser.hpp"        >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "08_cctmp_translator.hpp"    >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "09_cctmp_targeter.hpp"      >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "10_cctmp_metapiler.hpp"     >> "cpp_cctmp_library.hpp" &&

mawk "$mawk_prog_rest"  "undef_macros.hpp"           >> "cpp_cctmp_library.hpp"

