#!/bin/bash

mawk_prog_first='BEGIN { skip = 0; re_str = "^\/\*+\/$"; }
{
	if (skip)
	{
		if (!match($0, re_str)) skip = 0;
	}
	else if (match($0, re_str)) skip = 1;
	else print $0;
}'

mawk_prog_rest='BEGIN { line = 0; skip = 0; re_str = "^\/\*+\/$"; }
{
	if (line < 19) ++line;
	else
	{
		if (skip)
		{
			if (!match($0, re_str)) skip = 0;
		}
		else if (match($0, re_str)) skip = 1;
		else print $0;
	}
}'

mawk "$mawk_prog_first" "define_macros.hpp"          >  "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "00_cctmp_grammar.hpp"       >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "01_cctmp_block.hpp"         >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "02_cctmp_machine.hpp"       >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "03_cctmp_functional.hpp"    >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "05_generic_assembly.hpp"    >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "07_one_cycle_assembly.hpp"  >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "08_one_cycle_specifics.hpp" >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "09_one_cycle_accords.hpp"   >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "10_one_cycle_generics.hpp"  >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "undef_macros.hpp"           >> "cpp_cctmp_library.hpp"

