#!/bin/bash

mawk_prog_first='BEGIN { skip = 0; }
{
	if (skip)
	{
		if (!match($0, "^\/\*+\/$")) skip = 0;
	}
	else if (match($0, "^\/\*+\/$")) skip = 1;
	else print $0;
}'

mawk_prog_rest='BEGIN { line = 0; skip = 0; }
{
	if (line < 19) ++line;
	else
	{
		if (skip)
		{
			if (!match($0, "^\/\*+\/$")) skip = 0;
		}
		else if (match($0, "^\/\*+\/$")) skip = 1;
		else print $0;
	}
}'

mawk "$mawk_prog_first" "define_macros.hpp" >  "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "0_backend.hpp"     >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "1_frontend.hpp"    >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "2_programs.hpp"    >> "cpp_cctmp_library.hpp" &&
mawk "$mawk_prog_rest"  "undef_macros.hpp"  >> "cpp_cctmp_library.hpp"

