/************************************************************************************************************************
**
** Copyright 2022-2024 Daniel Nikpayuk, Inuit Nunangat, The Inuit Nation
**
** This file is part of cpp_cctmp_library.
**
** cpp_cctmp_library is free software: you can redistribute it and/or modify it under the terms
** of the GNU General Public License as published by the Free Software Foundation, either version 3
** of the License, or (at your option) any later version.
**
** cpp_cctmp_library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
** without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
** See the GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License along with cpp_cctmp_library.
** If not, see <http://www.gnu.org/licenses/>.
**
************************************************************************************************************************/

// object:

	template<typename SizeType>
	struct T_contr_object_chord_change_of_base_printer_v0
	{
		using size_type = SizeType;

		using AN = assembly::AN;
		using AT = assembly::AT;

		constexpr static size_type value[][8] =
		{
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::hash       , AT::port      ,   5,   0,   0,   0,   0,   1 }, 
			{ AN::pad        , AT::select    ,   0,   1,   0,   0,   0,   1 }, 
			{ AN::pad        , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 203,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        ,  92,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        ,  87,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  11,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   0,   2,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  15,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  24,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,   5,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  28,   1,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  33,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   5,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  42,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  13,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  46,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  51,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   5,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::next       , AT::inc       ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::next       , AT::dec       ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  64,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   0,   1,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  68,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::next       , AT::side      ,  62,  22,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::out_in_ins , AT::pred      ,  40,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::out_in_ins , AT::act_mut   ,   9,  22,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   3,   3,   0,   0,   0,   1 }, 
			{ AN::next       , AT::cont      ,  58,   1,   0,   0,   0,   1 }, 
			{ AN::next       , AT::cont      ,  75,   3,   0,   0,   0,   1 }, 
			{ AN::next       , AT::end       ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::cycle      , AT::side      ,  79,  81,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::cycle      , AT::id        ,  77,  86,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 171,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 164,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  98,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  26,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 102,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 111,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 115,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  27,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 119,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   6,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 126,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   5,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 135,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  13,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 139,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 144,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   5,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   3,   3,   0,   0,   0,   1 }, 
			{ AN::next       , AT::cont      ,  60,   2,   0,   0,   0,   1 }, 
			{ AN::next       , AT::end       ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::out_ins    , AT::pred      , 133,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::out_ins    , AT::act_mut   ,  96, 109,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   3,   3,   0,   0,   0,   1 }, 
			{ AN::next       , AT::cont      ,  60,   2,   0,   0,   0,   1 }, 
			{ AN::next       , AT::end       ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::cycle      , AT::side      , 157, 159,   0,   0,   0,   1 }, 
			{ AN::cycle      , AT::front     , 151,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::cycle      , AT::id        , 155, 163,   0,   0,   0,   1 }, 
			{ AN::cycle      , AT::act       , 157,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::id        ,   7,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 174,   1,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   1,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 179,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::type       , AT::n_number  ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::literal    , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   3,   3,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::id        ,  94,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 189,   0,   0,   0,   0,   3 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 192,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   1,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 197,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   0,   3,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   3,   3,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   1,   1,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 } 
		};

	}; template<typename SizeType>
		constexpr auto contr_object_chord_change_of_base_printer_v0 = cctmp::U_store_T
		<
			T_contr_object_chord_change_of_base_printer_v0<SizeType>
		>;

