/************************************************************************************************************************
**
** Copyright 2022-2024 Daniel Nikpayuk, Inuit Nunangat, The Inuit Nation
**
** This file is part of cpp_cctmp_library.
**
** cpp_cctmp_library is free software: you can redistribute it and/or modify it under the terms
** of the GNU General Public License as published by the Free Software Foundation, either version 3
** of the License, or (at your option) any later version.
**
** cpp_cctmp_library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
** without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
** See the GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License along with cpp_cctmp_library.
** If not, see <http://www.gnu.org/licenses/>.
**
************************************************************************************************************************/

// object:

	template<typename SizeType>
	struct T_contr_object_hustle_square_root_v1
	{
		using size_type = SizeType;

		using AN = assembly::AN;
		using AT = assembly::AT;

		constexpr static size_type value[][8] =
		{
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::hash       , AT::id        ,   5,   0,   0,   0,   0,   1 }, 
			{ AN::pad        , AT::select    ,   0,   1,   0,   0,   0,   1 }, 
			{ AN::pad        , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 196,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        ,  24,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,   9,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  14,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  13,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  18,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        ,  56,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  28,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,   8,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  32,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::invert     , AT::id        ,  50,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  40,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  13,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  44,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        ,  55,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::first     ,  52,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        ,  91,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  60,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,   8,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::id        ,  26,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  65,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  13,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::id        ,   7,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  70,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   2,   7,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  77,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   6,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   2,   5,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  86,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 116,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  95,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  15,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      ,  99,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  12,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 103,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 108,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   5,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   4,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 143,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::id        ,  93,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 121,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 126,   0,   0,   0,   0,   4 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::lookup     , AT::first     ,   1,  15,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 130,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 135,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   6,   0,   0,   0,   0,   1 }, 
			{ AN::apply      , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   2,   4,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 187,   0,   0,   0,   0,   1 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::id        ,  58,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 148,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 153,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   2,   4,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::invert     , AT::id        , 165,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::first     , 161,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::go_to      , AT::id        , 186,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::port      , 145,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::id        , 118,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 169,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   2,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 174,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   2,   5,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::back      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 181,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   3,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   2,   4,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::pound      , AT::port      , 145,   0,   0,   0,   0,   1 }, 
			{ AN::eval       , AT::back      , 190,   0,   0,   0,   0,   5 }, 
			{ AN::id         , AT::id        ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::select    ,   1,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::drop      ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   2,   2,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::arg        , AT::verse     ,   1,   1,   0,   0,   0,   1 }, 
			{ AN::bind       , AT::first     ,   0,   0,   0,   0,   0,   1 }, 
			{ AN::halt       , AT::first     ,   0,   0,   0,   0,   0,   1 } 
		};

	}; template<typename SizeType>
		constexpr auto contr_object_hustle_square_root_v1 = cctmp::U_store_T
		<
			T_contr_object_hustle_square_root_v1<SizeType>
		>;

